evaluations/urls.py
from django.conf.urls import url
from . import views

app_name = 'evaluations'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tutorial/$', views.tutorial, name='tutorial'),
    url(r'^testscene/$', views.testscene, name='testscene'),
    url(r'^info/$', views.info, name='info'),
    url(r'^scene/(?P<scene_id>[1-9]+)/$', views.scene, name='scene'),
    url(r'^scene/(?P<scene_id>[1-9]+)/rate/$', views.rate, name='rate'),
    url(r'^end/$', views.end, name='end'),
    url(r'^end-nopa/$', views.end_nopa, name='end-nopa'),
] 

image_quality_evaluation/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('evaluations.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^evaluations/', include('evaluations.urls')),
    url(r'^admin/', admin.site.urls),
] 

evaluations/models.py
import os
from django.db import models

# Create your models here.
class Observer(models.Model):
	name = models.CharField(max_length = 100)
	startTime = models.DateTimeField(null = True, name = 'evaluation_started')
	endTime = models.DateTimeField(null = True, name = 'evaluation_ended')

	def __str__(self):
		return str(self.name)

class Image(models.Model):
	scene = models.IntegerField(default = 0)
	image_file = models.ImageField(default = 'Null', upload_to = 'images')
	reference = models.BooleanField(default = False)
	hidden_reference = models.BooleanField(default = False)

	def __str__(self):
		return os.path.basename(getattr(self.image_file, 'name'))

class Rating(models.Model):
	observer = models.ForeignKey(Observer, on_delete = models.CASCADE)
	image = models.ForeignKey(Image, on_delete = models.CASCADE)
	dateTime = models.DateTimeField(blank = True, name = 'date_rated')
	score = models.IntegerField(default = 0)

evaluations/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from datetime import datetime
from django.core.urlresolvers import reverse
from .models import Image
from .models import Observer
from .models import Rating

def index(request):
	template = loader.get_template('evaluations/index.html')
	return HttpResponse(template.render(request))

def tutorial(request):
	template = loader.get_template('evaluations/tutorial.html')
	return HttpResponse(template.render(request))

def testscene(request):
	scene_reference_image = Image.objects.get(scene=0, reference=True)
	scene_image_list = Image.objects.filter(scene=0, reference=False)
	template = loader.get_template('evaluations/testscene.html')

	context = {	'scene_reference_image': scene_reference_image,
				'scene_image_list': scene_image_list,}

	return HttpResponse(template.render(context, request))

def info(request):
	template = loader.get_template('evaluations/info.html')
	return HttpResponse(template.render(request))

def scene(request, scene_id):

	if(int(scene_id) == 1):
		o = Observer(name = "Observer", evaluation_started = datetime.now())
		o.save()
		request.session['observer_id'] = o.id

	scene_reference_image = Image.objects.get(scene=scene_id, reference=True)
	scene_image_list = Image.objects.filter(scene=scene_id, reference=False)
	num_scenes = Image.objects.values_list('scene',flat = True).order_by('-scene')[:1][0]
	template = loader.get_template('evaluations/scene.html')

	if(int(scene_id) == num_scenes):
		last_scene = True
	else:
		last_scene = False

	context = {	'scene_reference_image': scene_reference_image,
				'scene_image_list': scene_image_list,
				'num_scenes': num_scenes, 
				'scene_id': scene_id ,
				'last_scene': last_scene,}
	return HttpResponse(template.render(context, request))

def rate(request, scene_id):
	scene_images = Image.objects.filter(scene=scene_id)
	observer_id = request.session['observer_id']
	num_scenes = Image.objects.values_list('scene',flat = True).order_by('-scene')[:1][0] 

	if(int(scene_id) == num_scenes):
		last_scene = True
	else:
		last_scene = False

	if request.method == 'POST':

		for image in scene_images:
			r = Rating(	observer_id=observer_id, 
						image_id=image.id, 
						date_rated=datetime.now(),
						score=request.POST.get('score-' + str(image.id), False))
			r.save()

		if(last_scene):
			return HttpResponseRedirect(reverse('evaluations:end'))
		else:
			return HttpResponseRedirect(reverse('evaluations:scene', args=(int(scene_id) + 1,)))


def end(request):
	observer_id = request.session['observer_id']
	o = Observer.objects.get(id=observer_id)
	o.evaluation_ended = datetime.now()
	o.save()

	template = loader.get_template('evaluations/end.html')
	return HttpResponse(template.render(request))

def end_nopa(request):
	template = loader.get_template('evaluations/end-nopa.html')
	return HttpResponse(template.render(request))

evaluations/templates/evaluations/end-nopa.html
{% extends "base.html" %}

{% block content %}
<h1>Tak for din interesse!</h1>
<div class="info-box">
	<p>
		Tusind tak for din interesse i at hjælpe mig med mit speciale. Desværre må jeg kun benytte evalueringer foretaget af personer, som ikke arbejder med billeder til daglig.
	</p>
	<p>
		Formålet med mit speciale er, at sammenligne billedkvalitetsevalueringer foretaget af mennesker med billedkvalitetsevalueringer foretaget af en computer. Ud fra denne sammenligning skal jeg anbefale den metode, hvor computerens billedkvalitetsevaluering stemmer bedst overens med menneskers evalueringer af billedkvalitet. Dette vil gøre det lettere og billigere for virksomheder, som arbejder med billeder, at få evalueret deres billedkvalitet.
	</p>
</div>
{% endblock %}

evaluations/templates/evaluations/end.html
{% extends "base.html" %}

{% block content %}
<h1>Tak for din hjælp!</h1>
<div class="info-box">
	<p>
		Du har nu fuldført billedkvalitetsevaluerongen. Tusind tak for din hjælp!
	</p>
	<p>
		Formålet med mit speciale er, at sammenligne billedkvalitetsevalueringer foretaget af mennesker med billedkvalitetsevalueringer foretaget af en computer. Ud fra denne sammenligning skal jeg anbefale den metode, hvor computerens billedkvalitetsevaluering stemmer bedst overens med menneskers evalueringer af billedkvalitet. Dette vil gøre det lettere og billigere for virksomheder, som arbejder med billeder, at få evalueret deres billedkvalitet.
	</p>
</div>
{% endblock %}

evaluations/templates/evaluations/index.html
{% extends "base.html" %}

{% block content %}
<h1>Velkommen til billedkvalitetsevalueringen</h1>
<div class="info-box">
	<p>
		I forbindelse med mit speciale på uddannelsen til Civilingeniør i Computer Teknologi ved Aarhus Universitet, skal jeg indsamle evalueringer af billedkvalitet. Evalueringerne består af to forskellige slags; vurderinger foretaget af mennersker, som ser billederne og vurderer kvaliteten, samt vurderinger fra en computer, som beregner kvaliteten på billederne.
	</p>
	<p>
		Jeg er utrolig glad for, at du har vist interesse for at hjælpe mig i mit speciale. Du skal være opmærksom på at denne evalueringssession tager mellem 15 og 20 minutter, hvilket jeg håber at du vil tage dig tid til.
	</p>
	<p>
		Du har desværre kun mulighed for at hjælpe mig med dette, hvis du ikke arbejder med billeder til daglig (er fotograf eller lign.). Derfor er jeg nødt til at spørge dig - arbejder du med billeder til daglig?
	</p>
</div>
<div class="index-buttons">
	<a href="/tutorial/" class="button"><span class="emph">NEJ</span>, jeg arbejder <span class="emph">IKKE</span> med billeder til daglig</a>
	<a href="/end-nopa/" class="button"><span class="emph">JA</span>, jeg arbejder med billeder til daglig</a>
</div>
{% endblock %}

evaluations/templates/evaluations/info.html
{% extends "base.html" %}

{% block content %}
<h1>Så starter vi ...</h1>
<div class="info-box">
	<p>
		Nu har du set hvordan det foregår, samt prøvet at vurdere nogle billeder. Når du klikker på "Start evaluering" behynder den rigtige evalueringssession.
	</p>
	<p>
		God fornøjelse!
	</p>
</div>
<a href="/scene/1/" class="button">Start evaluering</a>
{% endblock %}

evaluations/templates/evaluations/scene.html
{% extends "base.html" %}
{% load evaluation_extras %}

{% block content %}
<div id="scene-information">
	<p>Billedkvalitetsevaluering</p>
	<p><span>Scene:</span> {{scene_id}}/{{num_scenes}}</p>
</div>

<div id="image-box">
	<div id="tabs">
		<div id="tab-ref" class="tab-content tab-current">
			<div class="img">
				<img src="/media/{{ scene_reference_image.image_file }}" alt="{{ scene_reference_image.image_file }}">
			</div>
			<div class="rating">
				<input class="score" id="score-{{scene_reference_image.id}}" type="text" readonly>
				<div class="slider" id="slider-{{scene_reference_image.id}}"></div>
				<ul>
					<li>Fremragende</li>
					<li>God</li>
					<li>Acceptabel</li>
					<li>Middelmådig</li>
					<li>Dårlig</li>
				</ul>
			</div>
		</div>
		{% for image in scene_image_list %}
		<div id="tab-{{image.id}}" class="tab-content">
			<div class="img">
				<img src="/media/{{ image.image_file }}" alt="{{ image.image_file }}">
			</div>
			<div class="rating">
				<input class="score" id="score-{{image.id}}" type="text" readonly>
				<div class="slider" id="slider-{{image.id}}"></div>
				<ul>
					<li>Fremragende</li>
					<li>God</li>
					<li>Acceptabel</li>
					<li>Middelmådig</li>
					<li>Dårlig</li>
				</ul>
			</div>
		</div>
		{% endfor %}


	</div>
	<div id="navigation">
		<form action="{% url 'evaluations:rate' scene_id %}" method="post">
		{% csrf_token %}
		<ul>
			<li class="button tab-link button-current" data-tab="tab-ref">Reference<input class="navigation-score" name="score-{{scene_reference_image.id}}" value="x"/></li>
			{% for image in scene_image_list %}
			<li class="button tab-link" data-tab="tab-{{image.id}}">{{ forloop.counter|to_char }}<input class="navigation-score" name="score-{{image.id}}" value="x"></li>
			{% endfor %}
		</ul>

		{% if last_scene %}
		<input type="submit" class="button next-scene button-disabled" value="Afslut evalueringssession"/>
		{% else %}
		<input type="submit" class="button next-scene button-disabled" value="Næste scene"/>
		{% endif %}
	</div>
</div>
{% endblock %}

evaluations/templates/evaluations/testscene.html
{% extends "base.html" %}
{% load evaluation_extras %}

{% block content %}
<div id="scene-information">
	<p>Billedkvalitetsevaluering - test scene</p>
	<p><span>Scene:</span> 1/1</p>
</div>

<div id="image-box">
	<div id="tabs">
		<div id="tab-ref" class="tab-content tab-current">
			<div class="img">
				<img src="/media/{{ scene_reference_image.image_file }}" alt="{{ scene_reference_image.image_file }}">
			</div>
			<div class="rating">
				<input class="score" id="score-{{scene_reference_image.id}}" type="text" readonly>
				<div class="slider" id="slider-{{scene_reference_image.id}}"></div>
				<ul>
					<li>Fremragende</li>
					<li>God</li>
					<li>Acceptabel</li>
					<li>Middelmådig</li>
					<li>Dårlig</li>
				</ul>
			</div>
		</div>
		{% for image in scene_image_list %}
		<div id="tab-{{image.id}}" class="tab-content">
			<div class="img">
				<img src="/media/{{ image.image_file }}" alt="{{ image.image_file }}">
			</div>
			<div class="rating">
				<input class="score" id="score-{{image.id}}" type="text" readonly>
				<div class="slider" id="slider-{{image.id}}"></div>
				<ul>
					<li>Fremragende</li>
					<li>God</li>
					<li>Acceptabel</li>
					<li>Middelmådig</li>
					<li>Dårlig</li>
				</ul>
			</div>
		</div>
		{% endfor %}


	</div>
	<div id="navigation">
		<ul>
			<li class="button tab-link button-current" data-tab="tab-ref">Reference<input class="navigation-score" name="score-{{scene_reference_image.id}}" value="x"/></li>
			{% for image in scene_image_list %}
			<li class="button tab-link" data-tab="tab-{{image.id}}">{{ forloop.counter|to_char }}<input class="navigation-score" name="score-{{image.id}}" value="x"></li>
			{% endfor %}
		</ul>
		<a href="/info/" class="button next-scene button-disabled">Afslut testscene</a>
	</div>
</div>
{% endblock %}

evaluations/templates/evaluations/tutorial.html
{% extends "base.html" %}

{% block content %}
<h1>Instruktioner</h1>
<div class="info-box">
	<table class="instructions">
		<tr>
			<td>
				<p>
					Inden du starter på evalueringen kommer der her nogle instruktioner. Evalueringen er delt ind i flere scener. Et eksempel på en scene kan ses på billedet til højre. En scene består af en antal billeder, som alle skal evalueres inden man kan gå videre til næste scene. I alle scener vil der være et referencebillede. Referencebilledet er det oprindelige billede, men skal alligevel evalueres. Det første billede i en scene vil altid være referencebilledet.
				</p>
			</td>
			<td>
				<img src="/static/img/instruction1.png" alt="Instruction1">
			</td>
		</tr>
		<tr>
			<td>
				<img src="/static/img/instruction2.png" alt="Instruction2">
			</td>
			<td>
				<p>
					Du kan navigerer imellem de forskellige billeder ved hjælp af navigationsknapperne under billedet. Knappen "Reference" navigerer altid til referencebilledet. De resterende knapper navigerer til andre billeder. Når en ny scene startes, vil der under hver navigationsknap vises et "X". Når du har evalueret kvaliteten på et billede, vil dette "X" blive erstattet af den score, som du har vurderet billedets kvalitet til.
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					Til at bedømme kvaliteten af et billede anvendes en slider placeret til højre for billedet. Denne slider kan bruges til at justere den score, som du mener passer til kvaliteten af billedet. Bedømmelsesskalaen går fra 0 til 100 og til hjælp er fem kategorier fordelt ligeligt over hele skalaen. Scoren svarende til sliderens placering kan aflæses over slideren og under den navigationsknap, som refererer til billedet. 
				</p>
			</td>
			<td>
				<img src="/static/img/instruction3.png" alt="Instruction3">
			</td>
		</tr>
		<tr>
			<td>
				<img src="/static/img/instruction4.png" alt="Instruction4">
			</td>
			<td>
				<p>
					I øverste højre hjørne finder du en oversigt over, hvor langt du er i evalueringssessionen. Her kan du se, hvilken scene du er ved, samt hvor mange scener der er i alt.
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<p>
					Når alle billeder i en scene er evalueret, kan denne scene afsluttes. Dette gøres ved at klikke på knappen i højre side under billedet. Afhængig af hvilken scene du er ved vil teksten variere.
				</p>
				<p>
					Du vil nu blive navigeret til en testscene, hvor du kan prøve at udføre en evaluering, inden den rigtige evaluering starter. God fornøjelse!
				</p>
			</td>
			<td>
				<img src="/static/img/instruction5.png" alt="Instruction5">
			</td>
		</tr>
	</table>
</div>
<a href="/testscene/" class="button">Start testevaluering</a>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
	<!-- Metadata -->
	<title>Billedkvalitetsevaluering</title>
	<link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css" >
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet' type='text/css'> 
	<link href="{% static 'vendor/jquery-ui/jquery-ui.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" >

</head>
<body>
	<div id="container">
		{% block content %}{% endblock %}
	</div>
	<div id="mobile-container">
		<h1>Velkommen til billedkvalitetsevaluering</h1>
		<div class="info-box">
			<p>Ups, der er opstået et problem...</p>
			<p>... enten ser du denne hjemmeside på din mobil eller tablet. Denne billedkvalitetsevaluering kan desværre kun udføres på en computer. I så fald håber jeg at du vil komme tilbage og udføre den på et andet tidspunkt, når du sidder ved en computer.</p>
			<p>... eller også er dit browservindue for smalt. I så fald vil jeg foreslå at du maksimerer browservinduet. Dette burde gøre det muligt for dig at udføre billedkvalitetsevalueringen.</p>
		</div>
	</div>
</body>
<script type="text/javascript" src="{% static 'vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'vendor/jquery-ui/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>